<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-IIBVRVE9" failures="1" tests="4" name="Error Validation" time="74.905" errors="0" timestamp="2025-10-23T20:55:57 IST">
  <testcase classname="Framework.Framework.ErrorValidation" name="inCorrectCredValidation" time="3.597"/>
  <testcase classname="Framework.Framework.ErrorValidation" name="productErrValidation" time="5.24">
    <skipped/>
  </testcase> <!-- productErrValidation -->
  <testcase classname="Framework.Framework.ErrorValidation" name="productErrValidation" time="7.247">
    <skipped/>
  </testcase> <!-- productErrValidation -->
  <testcase classname="Framework.Framework.ErrorValidation" name="productErrValidation" time="14.09">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Framework.Framework.ErrorValidation.productErrValidation(ErrorValidation.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- productErrValidation -->
</testsuite> <!-- Error Validation -->
